// Generated by Haxe 3.3.0
if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
(function () { "use strict";
var com_p24studio_cardgame_main_constants_Rules = function() { };
com_p24studio_cardgame_main_constants_Rules.loadRules = function(configFilePath) {
	var rules = JSON.parse(js_node_Fs.readFileSync(configFilePath,{ encoding : "utf8"}));
	com_p24studio_cardgame_main_constants_Rules.isRulesObjectValid(rules);
	com_p24studio_cardgame_main_constants_Rules.maxCardsHand = rules.maxCardsHand;
	com_p24studio_cardgame_main_constants_Rules.playerDefaultLife = rules.playerDefaultLife;
};
com_p24studio_cardgame_main_constants_Rules.isRulesObjectValid = function(rules) {
	if(rules.maxCardsHand == null || rules.playerDefaultLife == null) {
		console.log("Invalid rules");
	}
};
var com_p24studio_cardgame_test_NodeMain = function() { };
com_p24studio_cardgame_test_NodeMain.main = function() {
	js_node_Http.createServer(function(req,res) {
		res.writeHead(200,{ 'Content-Type' : "text/plain"});
		res.end("Hello World\n");
	}).listen(1337,"127.0.0.1");
	console.log("Server running at http://127.0.0.1:1337/");
};
var haxe_io_Bytes = function() { };
var js_node_Fs = require("fs");
var js_node_Http = require("http");
var js_node_buffer_Buffer = require("buffer").Buffer;
com_p24studio_cardgame_test_NodeMain.main();
})();
